### ISSUE TITLE
pI mismatch between pIR and ExPASy server. pKa sets references?

### ISSUE THREAD

**Issue by andreyfrolov1** [ypriverol/pIR#4]
Dear Prof. Perez-Riverol,

I am using your tool for isoelectric point calculation “pIR” cited in http://bioinformatics.oxfordjournals.org/content/early/2015/11/13/bioinformatics.btv674.short
I found that the predictions of your tool with ExPASy set are sometimes different from the values produced by ExPASy server.  

**http://web.expasy.org/cgi-bin/compute_pi/pi_tool**
Compute pI/Mw
Theoretical pI/Mw (average) for the user-entered sequence:
GGGGD 
Theoretical pI/Mw: *_3.80 *_/ 361.31 

**pIR**

> seq <- "GGGGD"
> pI <- computeAllBjellValues(seq = seq)
> ^[pI
>       method values
> **1     expasy 4.2994**
> 2      skoog 2.9750
> 3 calibrated 4.2994
> 4      bjell 3.0799

I would appreciate very much if you could clarify the following: 

1) I see that you have different pKa values for NH2 and COOH termini groups for different residues. Could you please let me know from where you get these values, because I can not find them in the publications? 

2) the BJELL_CALIBRATED set in your publication is referred to the optimized set in paper Gauci et al. Proteomics 2008, 8, 4898. However, this optimized set provides different pKa values for some residues depending on whether they are located at the end of sequence or in the middle of the sequence. I could not find an indication of discrimination of end and middle position of residues in your code. Could you please be so kind to clarify what is the BJELL_CALIBRATED set in your publication.

Thank you very much.
With kindest regards,
Andrey

---

Andrey Frolov
Computational Chemist
AstraZeneca
R&D | Innovative Medicines (iMed) | Cardiovascular and Metabolic Diseases (CVMD)

**Comment by ypriverol** [comment]
@andreyfrolov1 thanks for using our library. Here my comments in line:
First we clean some of the code because we have some bugs in the present version. 

> seq <- "GGGGD"
> pIBjell(sequence = seq, pkSetMethod = "expasy")
> [1] 3.7998

We have a bug in the library that included the contribution of the N-term and C-term of the amino-acids in the expasy which was a bug because this is only possible in calibrated as we discuss in our two manuscripts. The present version of the package is fixed. You can find the pka contributions here:
  N Term: https://github.com/ypriverol/pIR/blob/master/R/pkSets.R#L79
  C Term: https://github.com/ypriverol/pIR/blob/master/R/pkSets.R#L102
  In the sequence: https://github.com/ypriverol/pIR/blob/master/R/pkSets.R#L136

About the Gauci contribution, we got the values from the original manuscript (http://onlinelibrary.wiley.com/doi/10.1002/pmic.200800295/abstract) and by contacting the authors. We tested all the peptides in the supplementary information 
(http://api.onlinelibrary.wiley.com/asset/v1/doi/10.1002%2Fpmic.200800295/asset/supinfo%2Fpmic_200800295_sm_tables.xls) of the original paper and the values are the same.

**Comment by ypriverol** [comment]
@andreyfrolov1 Can you let us know how the new version of the library works for you. I will close the issue if everything is OK.

**Comment by andreyfrolov1** [comment]
Thanks a lot. I am sorry, I don't have time ow to test the tool. I am sure that your bug fix is fine. So please close the ticket.
